name = "kafka-connector"
title = "MongoDB Kafka Connector"
intersphinx = ["https://docs.mongodb.com/manual/objects.inv"]

toc_landing_pages = ["/sink-connector", "/sink-connector/configuration-properties"]
