name = "kafka-connector"
title = "MongoDB Kafka Connector"
intersphinx = ["https://docs.mongodb.com/manual/objects.inv"]
toc_landing_pages = ["/introduction", "/sink-connector", "/source-connector", "/sink-connector/configuration-properties", "/source-connector/configuration-properties", "/sink-connector/fundamentals", "/source-connector/fundamentals", "/source-connector/usage-examples", "/security-and-authentication", "/troubleshooting"]

[constants]
mkc = "MongoDB Kafka Connector"
connector-long = "MongoDB Connector for Apache Kafka"
ak = "Apache Kafka"
kc = "Kafka Connect"
avro = "Apache Avro"
avro-short = "Avro"
kafka-connect = "Confluent Kafka Connect"
connector_version="1.2"
sink-connector="MongoDB Kafka sink connector"
source-connector="MongoDB Kafka source connector"
pipeline-size = "2.4 GB"
