name = "kafka-connector"
title = "MongoDB Kafka Connector"
intersphinx = ["https://docs.mongodb.com/manual/objects.inv"]
toc_landing_pages = ["/introduction", "/tutorials", "/sink-connector", "/source-connector", "/sink-connector/configuration-properties", "/source-connector/configuration-properties", "/sink-connector/fundamentals", "/source-connector/fundamentals", "/source-connector/usage-examples", "/security-and-authentication", "/troubleshooting"]

[constants]
mkc = "MongoDB Kafka Connector"
connector-long = "MongoDB Connector for Apache Kafka"
ak = "Apache Kafka"
kc = "Kafka Connect"
avro = "Apache Avro"
avro-short = "Avro"
kafka-connect = "Confluent Kafka Connect"
connector_version="1.7"
connector_patch_version="0"
connector_driver_version="4.5"
connector_version_github_tag="r{+connector_version+}.{+connector_patch_version+}"
sink-connector="MongoDB Kafka sink connector"
source-connector="MongoDB Kafka source connector"
connector_driver_url_base="https://docs.mongodb.com/drivers/java/sync/v{+connector_driver_version+}/"
connector_driver_api_doc_url_base="https://mongodb.github.io/mongo-java-driver/{+connector_driver_version+}/"
pipeline-size = "2.4 GB"
stable-api = "Stable API"
default-heartbeat-topic = "__mongodb_heartbeats"
query-api = "MongoDB Query API"

write-exception-version="1"
write-concern-exception-version="1"
