name = "kafka-connector"
title = "MongoDB Kafka Connector"
intersphinx = ["https://docs.mongodb.com/manual/objects.inv"]
toc_landing_pages = ["/introduction", "/tutorials", "/sink-connector", "/source-connector", "/sink-connector/configuration-properties", "/source-connector/configuration-properties", "/sink-connector/fundamentals", "/source-connector/fundamentals", "/source-connector/usage-examples", "/security-and-authentication", "/troubleshooting"]

[constants]
mkc = "MongoDB Kafka Connector"
connector-long = "MongoDB Connector for Apache Kafka"
ak = "Apache Kafka"
kc = "Kafka Connect"
avro = "Apache Avro"
avro-short = "Avro"
kafka-connect = "Confluent Kafka Connect"
connector_version="1.6"
connector_patch_version="1"
connector_driver_version="4.3"
connector_version_github_tag="r{+connector_version+}.{+connector_patch_version+}"
connector_kafka_version_major="2"
connector_kafka_version_minor="6"
connector_kafka_version_docs="https://kafka.apache.org/{+connector_kafka_version_major+}{+connector_kafka_version_minor+}"
sink-connector="MongoDB Kafka sink connector"
source-connector="MongoDB Kafka source connector"
connector_driver_url_base="https://docs.mongodb.com/drivers/java/sync/v{+connector_driver_version+}/"
pipeline-size = "2.4 GB"
stable-api = "Stable API"
default-heartbeat-topic = "__mongodb_heartbeats"
