name = "kafka-connector"
title = "MongoDB Kafka Connector"
intersphinx = ["https://docs.mongodb.com/manual/objects.inv"]
toc_landing_pages = ["/sink-connector", "/source-connector", "/sink-connector/configuration-properties", "/source-connector/configuration-properties", "/security-and-authentication"]

[constants]
mkc = "MongoDB Kafka Connector"
connector-long = "MongoDB Connector for Apache Kafka"
ak = "Apache Kafka"
kc = "Kafka Connect"
avro = "Apache Avro"
avro-short = "Avro"
kafka-connect = "Confluent Kafka Connect"
connector_version="1.6"
connector_driver_version="4.3"
sink-connector="MongoDB Kafka sink connector"
source-connector="MongoDB Kafka source connector"
connector_driver_url_base="https://docs.mongodb.com/drivers/java/sync/v{+connector_driver_version+}/"
pipeline-size = "2.4 GB"
